//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.24 at 09:02:03 PM BST 
//


package ie.gmit.sw.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for booking complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="booking">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="person" type="{http://sw.gmit.ie/model/}person"/>
 *         &lt;element name="bookingTimeFrame" type="{http://sw.gmit.ie/model/}bookingTimeFrame"/>
 *         &lt;element name="reservationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "booking", namespace = "http://sw.gmit.ie/model/", propOrder = {
    "_Id",
    "person",
    "bookingTimeFrame",
    "reservationTime"
})
public class Booking {

    @XmlElement(name = "_id", namespace = "http://sw.gmit.ie/model/", required = true)
    protected String _Id;
    @XmlElement(namespace = "http://sw.gmit.ie/model/", required = true)
    protected Person person;
    @XmlElement(namespace = "http://sw.gmit.ie/model/", required = true)
    protected BookingTimeFrame bookingTimeFrame;
    @XmlElement(namespace = "http://sw.gmit.ie/model/", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar reservationTime;

    /**
     * Gets the value of the _Id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String get_Id() {
        return _Id;
    }

    /**
     * Sets the value of the _Id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void set_Id(String value) {
        this._Id = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setPerson(Person value) {
        this.person = value;
    }

    /**
     * Gets the value of the bookingTimeFrame property.
     * 
     * @return
     *     possible object is
     *     {@link BookingTimeFrame }
     *     
     */
    public BookingTimeFrame getBookingTimeFrame() {
        return bookingTimeFrame;
    }

    /**
     * Sets the value of the bookingTimeFrame property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookingTimeFrame }
     *     
     */
    public void setBookingTimeFrame(BookingTimeFrame value) {
        this.bookingTimeFrame = value;
    }

    /**
     * Gets the value of the reservationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReservationTime() {
        return reservationTime;
    }

    /**
     * Sets the value of the reservationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReservationTime(XMLGregorianCalendar value) {
        this.reservationTime = value;
    }

}
