//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.24 at 07:06:57 PM BST 
//


package ie.gmit.sw.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for booking complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="booking">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="address" type="{http://sw.gmit.ie/model/}person"/>
 *         &lt;element name="car" type="{http://sw.gmit.ie/model/}person"/>
 *         &lt;element name="bookingTimeFrom" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="bookingTimeTo" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="reservationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "booking", namespace = "http://sw.gmit.ie/model/", propOrder = {
    "id",
    "address",
    "car",
    "bookingTimeFrom",
    "bookingTimeTo",
    "reservationTime"
})
public class Booking {

    @XmlElement(name = "_id", namespace = "http://sw.gmit.ie/model/", required = true)
    protected String id;
    @XmlElement(namespace = "http://sw.gmit.ie/model/", required = true)
    protected Person address;
    @XmlElement(namespace = "http://sw.gmit.ie/model/", required = true)
    protected Person car;
    @XmlElement(namespace = "http://sw.gmit.ie/model/", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar bookingTimeFrom;
    @XmlElement(namespace = "http://sw.gmit.ie/model/", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar bookingTimeTo;
    @XmlElement(namespace = "http://sw.gmit.ie/model/", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar reservationTime;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setAddress(Person value) {
        this.address = value;
    }

    /**
     * Gets the value of the car property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getCar() {
        return car;
    }

    /**
     * Sets the value of the car property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setCar(Person value) {
        this.car = value;
    }

    /**
     * Gets the value of the bookingTimeFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBookingTimeFrom() {
        return bookingTimeFrom;
    }

    /**
     * Sets the value of the bookingTimeFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBookingTimeFrom(XMLGregorianCalendar value) {
        this.bookingTimeFrom = value;
    }

    /**
     * Gets the value of the bookingTimeTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBookingTimeTo() {
        return bookingTimeTo;
    }

    /**
     * Sets the value of the bookingTimeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBookingTimeTo(XMLGregorianCalendar value) {
        this.bookingTimeTo = value;
    }

    /**
     * Gets the value of the reservationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReservationTime() {
        return reservationTime;
    }

    /**
     * Sets the value of the reservationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReservationTime(XMLGregorianCalendar value) {
        this.reservationTime = value;
    }

}
