//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.24 at 09:02:03 PM BST 
//


package ie.gmit.sw.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for bookingTimeFrame complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bookingTimeFrame">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bookingTimeFrom" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="bookingTimeTo" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bookingTimeFrame", namespace = "http://sw.gmit.ie/model/", propOrder = {
    "bookingTimeFrom",
    "bookingTimeTo"
})
public class BookingTimeFrame {

    @XmlElement(namespace = "http://sw.gmit.ie/model/", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar bookingTimeFrom;
    @XmlElement(namespace = "http://sw.gmit.ie/model/", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar bookingTimeTo;

    /**
     * Gets the value of the bookingTimeFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBookingTimeFrom() {
        return bookingTimeFrom;
    }

    /**
     * Sets the value of the bookingTimeFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBookingTimeFrom(XMLGregorianCalendar value) {
        this.bookingTimeFrom = value;
    }

    /**
     * Gets the value of the bookingTimeTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBookingTimeTo() {
        return bookingTimeTo;
    }

    /**
     * Sets the value of the bookingTimeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBookingTimeTo(XMLGregorianCalendar value) {
        this.bookingTimeTo = value;
    }

}
