//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.25 at 12:03:50 AM BST 
//


package ie.gmit.sw.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for booking complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="booking">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="person" type="{http://sw.gmit.ie/model/}person"/>
 *         &lt;element name="car" type="{http://sw.gmit.ie/model/}car"/>
 *         &lt;element name="bookingTimeFrame" type="{http://sw.gmit.ie/model/}bookingTimeFrame"/>
 *         &lt;element name="reservationTime" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "booking", namespace = "http://sw.gmit.ie/model/", propOrder = {
    "id",
    "person",
    "car",
    "bookingTimeFrame",
    "reservationTime"
})
public class Booking
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "_id", namespace = "http://sw.gmit.ie/model/", required = true)
    protected String id;
    @XmlElement(namespace = "http://sw.gmit.ie/model/", required = true)
    protected Person person;
    @XmlElement(namespace = "http://sw.gmit.ie/model/", required = true)
    protected Car car;
    @XmlElement(namespace = "http://sw.gmit.ie/model/", required = true)
    protected BookingTimeFrame bookingTimeFrame;
    @XmlElement(namespace = "http://sw.gmit.ie/model/")
    protected long reservationTime;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setPerson(Person value) {
        this.person = value;
    }

    /**
     * Gets the value of the car property.
     * 
     * @return
     *     possible object is
     *     {@link Car }
     *     
     */
    public Car getCar() {
        return car;
    }

    /**
     * Sets the value of the car property.
     * 
     * @param value
     *     allowed object is
     *     {@link Car }
     *     
     */
    public void setCar(Car value) {
        this.car = value;
    }

    /**
     * Gets the value of the bookingTimeFrame property.
     * 
     * @return
     *     possible object is
     *     {@link BookingTimeFrame }
     *     
     */
    public BookingTimeFrame getBookingTimeFrame() {
        return bookingTimeFrame;
    }

    /**
     * Sets the value of the bookingTimeFrame property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookingTimeFrame }
     *     
     */
    public void setBookingTimeFrame(BookingTimeFrame value) {
        this.bookingTimeFrame = value;
    }

    /**
     * Gets the value of the reservationTime property.
     * 
     */
    public long getReservationTime() {
        return reservationTime;
    }

    /**
     * Sets the value of the reservationTime property.
     * 
     */
    public void setReservationTime(long value) {
        this.reservationTime = value;
    }

}
