//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.25 at 12:03:50 AM BST 
//


package ie.gmit.sw.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bookingTimeFrame complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bookingTimeFrame">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bookingTimeFrom" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="bookingTimeTo" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bookingTimeFrame", namespace = "http://sw.gmit.ie/model/", propOrder = {
    "bookingTimeFrom",
    "bookingTimeTo"
})
public class BookingTimeFrame
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(namespace = "http://sw.gmit.ie/model/")
    protected long bookingTimeFrom;
    @XmlElement(namespace = "http://sw.gmit.ie/model/")
    protected long bookingTimeTo;

    /**
     * Gets the value of the bookingTimeFrom property.
     * 
     */
    public long getBookingTimeFrom() {
        return bookingTimeFrom;
    }

    /**
     * Sets the value of the bookingTimeFrom property.
     * 
     */
    public void setBookingTimeFrom(long value) {
        this.bookingTimeFrom = value;
    }

    /**
     * Gets the value of the bookingTimeTo property.
     * 
     */
    public long getBookingTimeTo() {
        return bookingTimeTo;
    }

    /**
     * Sets the value of the bookingTimeTo property.
     * 
     */
    public void setBookingTimeTo(long value) {
        this.bookingTimeTo = value;
    }

}
