//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.31 at 11:06:15 PM GMT 
//


package ie.gmit.sw.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for bookingTimeFrame complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="bookingTimeFrame"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="bookingTimeFrom" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="bookingTimeTo" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bookingTimeFrame", propOrder = {
        "bookingTimeFrom",
        "bookingTimeTo"
})
@XmlRootElement(name = "bookingTimeFrame")
public class BookingTimeFrame
        implements Serializable {

    private final static long serialVersionUID = 1L;
    protected long bookingTimeFrom;
    protected long bookingTimeTo;

    /**
     * Gets the value of the bookingTimeFrom property.
     */
    public long getBookingTimeFrom() {
        return bookingTimeFrom;
    }

    /**
     * Sets the value of the bookingTimeFrom property.
     */
    public void setBookingTimeFrom(long value) {
        bookingTimeFrom = value;
    }

    /**
     * Gets the value of the bookingTimeTo property.
     */
    public long getBookingTimeTo() {
        return bookingTimeTo;
    }

    /**
     * Sets the value of the bookingTimeTo property.
     */
    public void setBookingTimeTo(long value) {
        bookingTimeTo = value;
    }

}
