//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.31 at 11:06:15 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://sw.gmit.ie/model/")
package ie.gmit.sw.model;
